from chemlog.msol import msol

class Diketopiperazines(msol.MSOLDefinition):

    def name(self):
        return "Diketopiperazines"

    def __call__(self, n0: msol.Var1, n1: msol.Var1, n2: msol.Var1, n3: msol.Var1, n4: msol.Var1, n5: msol.Var1, n6: msol.Var1, n7: msol.Var1):
        return msol.NaryFormula(
            msol.BinaryConnective.CONJUNCTION,
            [
                msol.InSetFormula(n0, msol.Var2("N")),
                msol.InSetFormula(n1, msol.Var2("C")),
                msol.InSetFormula(n2, msol.Var2("C")),
                msol.InSetFormula(n3, msol.Var2("O")),
                msol.InSetFormula(n4, msol.Var2("N")),
                msol.InSetFormula(n5, msol.Var2("C")),
                msol.InSetFormula(n6, msol.Var2("C")),
                msol.InSetFormula(n7, msol.Var2("O")),
                msol.PredicateExpression("bSINGLE", [n0, n1]),
                msol.PredicateExpression("bSINGLE", [n1, n2]),
                msol.PredicateExpression("bDOUBLE", [n2, n3]),
                msol.PredicateExpression("bSINGLE", [n2, n4]),
                msol.PredicateExpression("bSINGLE", [n4, n5]),
                msol.PredicateExpression("bSINGLE", [n5, n6]),
                msol.PredicateExpression("bDOUBLE", [n6, n7]),
                msol.PredicateExpression("bSINGLE", [n0, n6]),
                msol.PredicateExpression("charge0", [n0]),
                msol.PredicateExpression("charge0", [n1]),
                msol.PredicateExpression("charge0", [n2]),
                msol.PredicateExpression("charge0", [n3]),
                msol.PredicateExpression("charge0", [n4]),
                msol.PredicateExpression("charge0", [n5]),
                msol.PredicateExpression("charge0", [n6]),
                msol.PredicateExpression("charge0", [n7]),
            ]
        )


class Emericellamide(msol.MSOLDefinition):

    def name(self):
        return "Emericellamide"

    # 34-ary predicate
    def __call__(self, n0: msol.Var1, n1: msol.Var1, n2: msol.Var1, n3: msol.Var1, n4: msol.Var1, n5: msol.Var1,
                 n6: msol.Var1, n7: msol.Var1, n8: msol.Var1, n9: msol.Var1, n10: msol.Var1, n11: msol.Var1,
                 n12: msol.Var1, n13: msol.Var1, n14: msol.Var1, n15: msol.Var1, n16: msol.Var1, n17: msol.Var1,
                 n18: msol.Var1, n19: msol.Var1, n20: msol.Var1, n21: msol.Var1, n22: msol.Var1, n23: msol.Var1,
                 n24: msol.Var1, n25: msol.Var1, n26: msol.Var1, n27: msol.Var1, n28: msol.Var1, n29: msol.Var1,
                    n30: msol.Var1, n31: msol.Var1, n32: msol.Var1, n33: msol.Var1):
        return msol.NaryFormula(
            msol.BinaryConnective.CONJUNCTION,
            [
                msol.InSetFormula(n0, msol.Var2("C")),
                msol.InSetFormula(n1, msol.Var2("O")),
                msol.InSetFormula(n2, msol.Var2("C")),
                msol.InSetFormula(n3, msol.Var2("O")),
                msol.InSetFormula(n4, msol.Var2("C")),
                msol.InSetFormula(n5, msol.Var2("C")),
                msol.InSetFormula(n6, msol.Var2("N")),
                msol.InSetFormula(n7, msol.Var2("C")),
                msol.InSetFormula(n8, msol.Var2("O")),
                msol.InSetFormula(n9, msol.Var2("C")),
                msol.InSetFormula(n10, msol.Var2("C")),
                msol.InSetFormula(n11, msol.Var2("N")),
                msol.InSetFormula(n12, msol.Var2("O")),
                msol.InSetFormula(n13, msol.Var2("C")),
                msol.InSetFormula(n14, msol.Var2("C")),
                msol.InSetFormula(n15, msol.Var2("C")),
                msol.InSetFormula(n16, msol.Var2("C")),
                msol.InSetFormula(n17, msol.Var2("C")),
                msol.InSetFormula(n18, msol.Var2("N")),
                msol.InSetFormula(n19, msol.Var2("C")),
                msol.InSetFormula(n20, msol.Var2("O")),
                msol.InSetFormula(n21, msol.Var2("C")),
                msol.InSetFormula(n22, msol.Var2("N")),
                msol.InSetFormula(n23, msol.Var2("C")),
                msol.InSetFormula(n24, msol.Var2("O")),
                msol.InSetFormula(n25, msol.Var2("C")),
                msol.InSetFormula(n26, msol.Var2("N")),
                msol.InSetFormula(n27, msol.Var2("C")),
                msol.InSetFormula(n28, msol.Var2("O")),
                msol.InSetFormula(n29, msol.Var2("O")),
                msol.InSetFormula(n30, msol.Var2("C")),
                msol.InSetFormula(n31, msol.Var2("C")),
                msol.InSetFormula(n32, msol.Var2("C")),
                msol.InSetFormula(n33, msol.Var2("C")),
                msol.InSetFormula(n0, msol.Var2("Charge0")),
                msol.InSetFormula(n1, msol.Var2("Charge0")),
                msol.InSetFormula(n2, msol.Var2("Charge0")),
                msol.InSetFormula(n3, msol.Var2("Charge0")),
                msol.InSetFormula(n4, msol.Var2("Charge0")),
                msol.InSetFormula(n5, msol.Var2("Charge0")),
                msol.InSetFormula(n6, msol.Var2("Charge0")),
                msol.InSetFormula(n7, msol.Var2("Charge0")),
                msol.InSetFormula(n8, msol.Var2("Charge0")),
                msol.InSetFormula(n9, msol.Var2("Charge0")),
                msol.InSetFormula(n10, msol.Var2("Charge0")),
                msol.InSetFormula(n11, msol.Var2("Charge0")),
                msol.InSetFormula(n12, msol.Var2("Charge0")),
                msol.InSetFormula(n13, msol.Var2("Charge0")),
                msol.InSetFormula(n14, msol.Var2("Charge0")),
                msol.InSetFormula(n15, msol.Var2("Charge0")),
                msol.InSetFormula(n16, msol.Var2("Charge0")),
                msol.InSetFormula(n17, msol.Var2("Charge0")),
                msol.InSetFormula(n18, msol.Var2("Charge0")),
                msol.InSetFormula(n19, msol.Var2("Charge0")),
                msol.InSetFormula(n20, msol.Var2("Charge0")),
                msol.InSetFormula(n21, msol.Var2("Charge0")),
                msol.InSetFormula(n22, msol.Var2("Charge0")),
                msol.InSetFormula(n23, msol.Var2("Charge0")),
                msol.InSetFormula(n24, msol.Var2("Charge0")),
                msol.InSetFormula(n25, msol.Var2("Charge0")),
                msol.InSetFormula(n26, msol.Var2("Charge0")),
                msol.InSetFormula(n27, msol.Var2("Charge0")),
                msol.InSetFormula(n28, msol.Var2("Charge0")),
                msol.InSetFormula(n29, msol.Var2("Charge0")),
                msol.InSetFormula(n30, msol.Var2("Charge0")),
                msol.InSetFormula(n31, msol.Var2("Charge0")),
                msol.InSetFormula(n32, msol.Var2("Charge0")),
                msol.InSetFormula(n33, msol.Var2("Charge0")),
                msol.PredicateExpression("cip_code_S", [n4]),
                msol.PredicateExpression("cip_code_S", [n9]),
                msol.PredicateExpression("cip_code_S", [n14]),
                msol.PredicateExpression("cip_code_S", [n22]),
                msol.PredicateExpression("bSINGLE", [n0, n1]),
                msol.PredicateExpression("bSINGLE", [n1, n2]),
                msol.PredicateExpression("bDOUBLE", [n2, n3]),
                msol.PredicateExpression("bSINGLE", [n2, n4]),
                msol.PredicateExpression("bSINGLE", [n4, n5]),
                msol.PredicateExpression("bSINGLE", [n4, n6]),
                msol.PredicateExpression("bSINGLE", [n6, n7]),
                msol.PredicateExpression("bDOUBLE", [n7, n8]),
                msol.PredicateExpression("bSINGLE", [n7, n9]),
                msol.PredicateExpression("bSINGLE", [n9, n10]),
                msol.PredicateExpression("bSINGLE", [n9, n11]),
                msol.PredicateExpression("bSINGLE", [n11, n12]),
                msol.PredicateExpression("bDOUBLE", [n12, n13]),
                msol.PredicateExpression("bSINGLE", [n12, n14]),
                msol.PredicateExpression("bSINGLE", [n14, n15]),
                msol.PredicateExpression("bSINGLE", [n15, n16]),
                msol.PredicateExpression("bSINGLE", [n16, n17]),
                msol.PredicateExpression("bSINGLE", [n16, n18]),
                msol.PredicateExpression("bSINGLE", [n14, n19]),
                msol.PredicateExpression("bSINGLE", [n19, n20]),
                msol.PredicateExpression("bDOUBLE", [n20, n21]),
                msol.PredicateExpression("bSINGLE", [n20, n22]),
                msol.PredicateExpression("bSINGLE", [n22, n23]),
                msol.PredicateExpression("bSINGLE", [n23, n24]),
                msol.PredicateExpression("bDOUBLE", [n24, n25]),
                msol.PredicateExpression("bSINGLE", [n24, n26]),
                msol.PredicateExpression("bSINGLE", [n26, n27]),
                msol.PredicateExpression("bSINGLE", [n27, n28]),
                msol.PredicateExpression("bDOUBLE", [n28, n29]),
                msol.PredicateExpression("bSINGLE", [n28, n30]),
                msol.PredicateExpression("bSINGLE", [n22, n31]),
                msol.PredicateExpression("bSINGLE", [n31, n32]),
                msol.PredicateExpression("bSINGLE", [n31, n33]),
                msol.PredicateExpression("bSINGLE", [n30, n0]),
                msol.PredicateExpression("has_at_least_1_hs", [n4]),
                msol.PredicateExpression("has_at_least_3_hs", [n5]),
                msol.PredicateExpression("has_at_least_1_hs", [n6]),
                msol.PredicateExpression("has_at_least_1_hs", [n9]),
                msol.PredicateExpression("has_at_least_3_hs", [n10]),
                msol.PredicateExpression("has_at_least_1_hs", [n11]),
                msol.PredicateExpression("has_at_least_1_hs", [n14]),
                msol.PredicateExpression("has_at_least_2_hs", [n15]),
                msol.PredicateExpression("has_at_least_1_hs", [n16]),
                msol.PredicateExpression("has_at_least_3_hs", [n17]),
                msol.PredicateExpression("has_at_least_3_hs", [n18]),
                msol.PredicateExpression("has_at_least_1_hs", [n19]),
                msol.PredicateExpression("has_at_least_1_hs", [n22]),
                msol.PredicateExpression("has_at_least_1_hs", [n23]),
                msol.PredicateExpression("has_at_least_2_hs", [n26]),
                msol.PredicateExpression("has_at_least_1_hs", [n27]),
                msol.PredicateExpression("has_at_least_1_hs", [n31]),
                msol.PredicateExpression("has_at_least_3_hs", [n32]),
                msol.PredicateExpression("has_at_least_3_hs", [n33]),
            ]
        )